---
- name: Set hostname in VM
  ansible.builtin.shell: |
    tart exec {{ inventory_hostname }} sh -c "sudo hostnamectl set-hostname {{ inventory_hostname }}"
  delegate_to: localhost

- name: Set ssh public key
  ansible.posix.authorized_key:
    user: admin
    state: present
    key: "{{ ssh_public_key }}"
  vars:
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}" 
  
- name: Ensure all inventory hosts are in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_host | default(item) }} {{ item }}"
    state: present
    backup: true
    regexp: "^{{ hostvars[item].ansible_host | default(item) }}\\s+{{ item }}"
  loop: "{{ groups['all'] | difference(['localhost']) }}"
  become: true
  delegate_to: localhost
