---
- name: Detect primary interface name inside guest
  ansible.builtin.shell: |
    tart exec {{ inventory_hostname }} ip -o link show | awk -F':' '{print $2}' | grep -v lo | head -n1
  register: iface
  changed_when: false
  delegate_to: localhost

- name: Set ip address for each VM
  ansible.builtin.shell: |
    NIC=$(tart exec {{ inventory_hostname }} ip -o link show | awk -F":" '{print $2}' | grep -v lo);
    tart exec {{ inventory_hostname }} sudo ip address flush dev $NIC;
    tart exec {{ inventory_hostname }} sudo ip address add {{ ansible_host }}/24 dev $NIC;
  delegate_to: localhost

- name: Render netplan of each VM
  ansible.builtin.template:
    src: netplan.yaml.j2
    dest: "/tmp/{{ inventory_hostname }}-netplan.yaml"
    mode: '0644'
  delegate_to: localhost
  vars:
    iface_name: "{{ iface.stdout | trim }}"
    vm:
      ip: "{{ ansible_host }}"

- name: Copy rendered netplan to each VM
  ansible.builtin.copy:
    src: "/tmp/{{ inventory_hostname }}-netplan.yaml"
    dest: "/etc/netplan/"
    mode: '0644'
  delegate_to: "{{ inventory_hostname }}"
  become: true

- name: Apply netplan
  ansible.builtin.shell: |
    tart exec {{ inventory_hostname }} sh -c "sudo netplan apply"
  delegate_to: localhost