---
- name: Configure CPU and memory for VMs
  ansible.builtin.command:
    argv: [ "tart", "set", "{{ vm.name }}", "--cpu", "{{ vm.cpu }}", "--memory", "{{ vm.memory }}" ]
  loop: "{{ vms }}"
  loop_control:
    loop_var: vm
    label: "{{ vm.name }}"

- name: Run VM
  ansible.builtin.command:
    argv: [ "tart", "run", "--no-graphics", "{{ vm.name }}" ]
  loop: "{{ vms }}"
  loop_control:
    loop_var: vm
    label: "{{ vm.name }}"
  async: 86400
  poll: 0
  tags:
    - deploy
