---
- name: Configure CPU and memory for VMs
  ansible.builtin.command:
    argv: [ "tart", "set", "{{ item }}", "--cpu", "{{ hostvars[item].cpu }}", "--memory", "{{ hostvars[item].memory }}" ]
  loop: "{{ groups['all'] | difference(['localhost']) }}"
  loop_control:
    label: "{{ item }}"
  delegate_to: localhost
  tags:
    - deploy

- name: Run VM
  ansible.builtin.command:
    argv: [ "tart", "run", "--no-graphics", "{{ item }}" ]
  loop: "{{ groups['all'] | difference(['localhost'])}}"
  loop_control:
    label: "{{ item }}"
  async: 86400
  poll: 0
  tags:
    - deploy
