---
# Main task entry for Tart VM management

- name: Include prepare tasks
  ansible.builtin.import_tasks: prepare.yml
  tags:
    - prepare

- name: Include run tasks
  ansible.builtin.import_tasks: deploy.yml
  tags:
    - deploy

# - name: Include stop tasks
#   ansible.builtin.import_tasks: stop.yml
#   tags:
#     - stop

# - name: Include delete tasks
#   ansible.builtin.import_tasks: delete.yml
#   tags:
#     - remove
