---
- name: Stop VM
  ansible.builtin.command:
    argv: [ "tart", "stop", "{{ vm.name }}" ]
  loop: "{{ vms }}"
  loop_control:
    loop_var: vm
    label: "{{ vm.name }}"
  async: 86400
  poll: 0
  tags:
    - stop